### ISSUE TITLE
Variable referenced before assigning

### ISSUE THREAD

**Issue by rneher** [iosonofabio/seqanpy#1]
hi @iosonofabio 

is just installed seqanpy on the basel cluster and got errors when calling alignment routines (quite possibly a swig version issue). It complains that `seq1` is not defined in the statement `seq1="".join(seq1)` where `seq1` is supposed to be the first argument of the function. But swig defined the function as `align_overlap(*args, **kwargs)`

I removed the prepend statements for now and it works. but I thought you might want to know...

cheers,
richard

**Comment by iosonofabio** [comment]
Hi Richard,
You need SWIG 3.0.8+

Cheers
Fabio

**Comment by iosonofabio** [comment]
I could also make a binary with _manylinux and distribute it on Pypi but it'll take a month

**Comment by rneher** [comment]
thanks. just saw that swig 3.0.10 is in conda. this will work. thanks.
